version: "3.8"

services:
  taskmanager-db:
    container_name: taskmanager-db
    image: mysql:5.7
    networks:
      - taskmanager-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=taskmanagerdb
    volumes:
      - dbvol:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
  app:
    networks:
      - taskmanager-network
    depends_on:
      - taskmanager-db
    build: .
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://taskmanager-db:3306/taskmanagerdb?user=root&password=root
      SPRING_DATASOURCE_PASSWORD: 
    volumes:
      - .m2:/root/.m2

volumes:
  dbvol:

networks:
  taskmanager-network:
    driver: bridge